RISK_KEYWORDS = [
    "termination",
    "penalty",
    "indemnify",
    "liability",
    "compensation",
    "damages",
    "breach",
    "default",
    "waiver",
    "forfeit",
    "non-compliance",
    "sanctions",
    "confidentiality breach",
    "legal action",
    "dispute",
    "lawsuit",
    "fine",
    "interest",
    "reimbursement",
    "losses",
    "misrepresentation",
    "warranty breach",
    "negligence",
    "unilateral",
    "arbitration",
    "revocation",
    "termination for cause",
    "force majeure",
    "injunction",
    "specific performance",
    "indemnification",
    "severability",
    "liquidated damages",
    "non-performance"
]
